// lib/ae_dashboard/add_worker_screen.dart
import 'package:flutter/material.dart';
import 'package:cloud_firestore/cloud_firestore.dart';
import '../models/field_worker_model.dart';

class AddWorkerScreen extends StatefulWidget {
  const AddWorkerScreen({super.key});

  @override
  State<AddWorkerScreen> createState() => _AddWorkerScreenState();
}

class _AddWorkerScreenState extends State<AddWorkerScreen> {
  final _nameController = TextEditingController();
  final _contactController = TextEditingController();
  String _selectedRole = 'Wireman';

  // Roles exactly as per Department Hierarchy
  final List<String> _roles = [
    'Foreman',
    'Line Inspector',
    'Wireman',
    'Field Assistant / Mazdoor'
  ];

  Future<void> _saveWorker() async {
    if (_nameController.text.isEmpty) return;

    final worker = FieldWorkerModel(
      id: '', // Generated by Firestore
      name: _nameController.text.trim(),
      role: _selectedRole,
      section: 'Peelamedu Section', // AE's specific section [cite: 10]
      contact: _contactController.text.trim(),
    );

    await FirebaseFirestore.instance
        .collection('field_workers')
        .add(worker.toMap());

    if (mounted) Navigator.pop(context);
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(title: const Text("Register New Field Staff")),
      body: Padding(
        padding: const EdgeInsets.all(16.0),
        child: Column(
          children: [
            TextField(
              controller: _nameController,
              decoration: const InputDecoration(labelText: "Worker Full Name"),
            ),
            const SizedBox(height: 15),
            DropdownButtonFormField<String>(
              initialValue: _selectedRole,
              items: _roles.map((r) => DropdownMenuItem(value: r, child: Text(r))).toList(),
              onChanged: (val) => setState(() => _selectedRole = val!),
              decoration: const InputDecoration(labelText: "Designated Role"),
            ),
            const SizedBox(height: 15),
            TextField(
              controller: _contactController,
              decoration: const InputDecoration(labelText: "Contact Number"),
              keyboardType: TextInputType.phone,
            ),
            const Spacer(),
            ElevatedButton(
              onPressed: _saveWorker,
              child: const Center(child: Text("Add to Section Staff")),
            ),
          ],
        ),
      ),
    );
  }
}